### ISSUE TITLE
Release is necessary for integrating with Zig's Package Manager (build.zig.zon)

### ISSUE THREAD

**Issue by James-Riordan** [Snektron/vulkan-zig#111]
In order to use Zig's package manager to install this library as a project dependency, it's necessary to create releases. 

build.zig.zon required a tar.gz or tar.xz file.

**Comment by James-Riordan** [comment]
Ah yeah, my bad. I realized this after I opened the same issue on the openxr-zig repository. 

I think it would be beneficial to have releases with the respective hash posted as release notes. It would make the overhead of installing a dependency easier.

e.g copy and paste release/tar.gz and its hash

**Comment by Snektron** [comment]
That sounds fine. I'll make one after I resolve some of the other issues that were reported this week.
