### ISSUE TITLE
Commit to use with zig 0.11

### ISSUE THREAD

**Issue by Aleod-m** [Snektron/vulkan-zig#124]
The compat branch for zig 0.11 is missing. Here is the commit to use for 0.11: [commit](https://github.com/Snektron/vulkan-zig/tree/348ac5d35a859abd6e3db8b4190c75a417c1894b)

**Comment by Snektron** [comment]
Apologies for forgetting to do it last time. Now that 0.12 is released, there will not be a 0.11 tag. See https://github.com/Snektron/vulkan-zig/issues/130.
