### ISSUE TITLE
@fieldParentPtr() - error: expected 3 arguments, found 2

### ISSUE THREAD

**Issue by James-Riordan** [Snektron/vulkan-zig#128]
I see that recent changes were made to the `@fieldParentPtr` code in `generator/build_integration.zig` lines 77 & 171 in[ this commit](https://github.com/Snektron/vulkan-zig/commit/e84011929021cbcfd77a96e85f36bde5a6a6c81b). @igaryhe I'm not sure if this commit is related to my issue, but I seem to get this error when compiling with zig version `0.12.0-dev.3180+83e578a18`.

```
/.cache/zig/p/12203dd92af51de24d95545584c376f2d76698ff0b73d5e5b1cf0e1e12bba2ca4d48/generator/build_integration.zig:171:42: error: expected 3 arguments, found 2
        const self: *ShaderCompileStep = @fieldParentPtr("step", step);
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Did you run into something similar?

**Comment by igaryhe** [comment]
Hi James,
Can you try compiling with zig 0.12.0? This commit was intended to fix a breaking change made upstream: https://github.com/ziglang/zig/pull/19470

**Comment by James-Riordan** [comment]
@igaryhe hopped outta bed to test real quick, yep, it works for `12.0` and `0.13.0-dev.4+c7ffdbcd4`, but breaks for `0.12.0-dev.3180+83e578a18`. How weird! All good, I'll close the issue
