### ISSUE TITLE
Proxy wrappers

### ISSUE THREAD

**Issue by Snektron** [Snektron/vulkan-zig#131]
Several people have shown interest (a while ago already... oops) for a 'proxying' wrapper - A version of `InstanceWrapper` and `DeviceWrapper` which contain the dispatch type _and_ the functions, and automatically passes the dispatched type to the functions. I was relunctant to this at first, becuase I didn't want to have an asynchronousity in the API where core functions can be used with the wrapper, extensions can't (like with Ash). I realized that we don't have this issue, because we already have the functionality to select exactly which functions a user needs.

Concrete, there should be something like `InstanceProxy` and `DeviceProxy` which does whats described above. The current `InstanceWrapper` and `DeviceWrapper` will stay the same - these will then mainly be used for optional extensions where one passes the `proxy.handle` to.

**Comment by ashpil** [comment]
FYI I’ve been maintaining a fork that does exactly this for a while: https://github.com/ashpil/vulkan-zig/tree/wacky-wrappers

Might be useful as a reference.

**Comment by Snektron** [comment]
@ashpil see prototype above. It looks pretty decent, though double the code of course.
