### ISSUE TITLE
Wrappers for Vulkan functions returning an array

### ISSUE THREAD

**Issue by poconn** [Snektron/vulkan-zig#145]
For functions such as `vkEnumeratePhysicalDevices()` that return an array through two calls with the caller allocating space, it would be nice to have more idiomatic wrappers that return a slice using a user-provided allocator. A lot of other bindings provide something similar (e.g. vulkan-hpp and ash) and IMO it's such a common need and unopinionated enough that it's worth including even though vulkan-zig otherwise just directly maps to the C API.

If you agree this is in scope then I can take a shot at adding it, although I haven't looked at the generator too closely so I don't really have a sense of how involved it will be.

**Comment by Snektron** [comment]
Yea that'd be nice to have. I think it'd be relatively annoying to attempt to detect "allocation like functions" from render.zig, I'm fine with hardcoding a list of Vulkan functions like that.

**Comment by poconn** [comment]
Sounds good, thanks! I've roughly got it working, it needs a lot of cleanup before I post a PR but meanwhile I want to make sure the generated code looks alright. Here are a few examples.

For all functions I'm handling the case where the size changes between calls even though for most of them that can't actually happen, as the overhead is negligible and it doesn't seem worth maintaining a list of which functions need to deal with that. From what I've seen, other bindings out there seem to do the same ([example](https://github.com/KhronosGroup/Vulkan-Hpp/blob/d507727fd7df89ef08749d54e3ca87af238695a8/vulkan/vulkan_funcs.hpp#L127)).

```zig
// wrapped function returns a `VkResult`:
pub const EnumerateInstanceExtensionPropertiesAsSliceError =
    EnumerateInstanceExtensionPropertiesError || Allocator.Error;
pub fn enumerateInstanceExtensionPropertiesAsSlice(
    self: Self,
    p_layer_name: ?[*:0]const u8,
    allocator: Allocator,
) EnumerateInstanceExtensionPropertiesAsSliceError![]ExtensionProperties {
    var data: []ExtensionProperties = &.{};
    var count: u32 = undefined;
    var result = Result.incomplete;
    while (result == .incomplete) {
        _ = try self.enumerateInstanceExtensionProperties(p_layer_name, &count, null);
        data = try allocator.realloc(data, count);
        result = try self.enumerateInstanceExtensionProperties(p_layer_name, &count, data.ptr);
    }
    return if (count == data.len) data else allocator.realloc(data, count);
}

// wrapped function returns void:
pub fn getPhysicalDeviceQueueFamilyPropertiesAsSlice(
    self: Self,
    physical_device: PhysicalDevice,
    allocator: Allocator,
) Allocator.Error![]QueueFamilyProperties {
    var count: u32 = undefined;
    self.getPhysicalDeviceQueueFamilyProperties(physical_device, &count, null);
    const data = try allocator.alloc(QueueFamilyProperties, count);
    self.getPhysicalDeviceQueueFamilyProperties(physical_device, &count, data.ptr);
    return if (count == data.len) data else allocator.realloc(data, count);
}
```

**Comment by Snektron** [comment]
That seems good!

**Comment by poconn** [comment]
Will do, I'll try to post a PR tomorrow or so.
