### ISSUE TITLE
Double Free?

### ISSUE THREAD

**Issue by Mr-Slurpy** [Snektron/vulkan-zig#18]
I was doing some tweaks to modify what code is generated and I noticed something strange.

Here we allocate the tags for id_renderer:
https://github.com/Snektron/vulkan-zig/blob/eb417c6aa0742b2f3c99679cb52d4bff9b10f416/generator/vulkan/generator.zig#L117

Here we deallocate the tags:
https://github.com/Snektron/vulkan-zig/blob/eb417c6aa0742b2f3c99679cb52d4bff9b10f416/generator/vulkan/generator.zig#L129

And here we deallocate the tags again:
https://github.com/Snektron/vulkan-zig/blob/eb417c6aa0742b2f3c99679cb52d4bff9b10f416/generator/vulkan/render.zig#L215-L216
But not only that, we also deallocate with a completely different allocator then what we started with.
Also we do `id_renderer.deinit()` but shouldn't that be happening in `Generator.deinit`? Like such:
```zig
self.gpa.free(self.id_renderer.tags);
self.id_renderer.deinit();
```
I'm not familiar with the code so I may be wrong, which is why I'm asking.

**Comment by Snektron** [comment]
At some point i moved the id renderer from the Renderer to Generator as i needed to get the vendor tags there as well, so i guess i had missed a few things there. Thanks for finding and reporting.
