### ISSUE TITLE
In case it's interesting to you

### ISSUE THREAD

**Issue by slimsag** [Snektron/vulkan-zig#23]
I ported the example here to use `mach-glfw`:

https://github.com/hexops/mach-glfw-vulkan-example

I figured it's nice to have this repo not have a dependency so I didn't send this as a PR.

Also, I will soon begin looking into cross-compiling Vulkan applications with [the system-sdk setup](https://github.com/hexops/mach-glfw/blob/main/system_sdk.zig) I am using and so maybe vulkan-zig will be cross-compilable soon. :)

**Comment by Snektron** [comment]
That is very nice.

> I figured it's nice to have this repo not have a dependency so I didn't send this as a PR.

Yes it doesn't seem like a good idea to add that dependency just for an example, but i shall add a link in the 'See also' section in the readme.
