### ISSUE TITLE
Enum tag types

### ISSUE THREAD

**Issue by InKryption** [Snektron/vulkan-zig#26]
I've noticed that enums tag types are always rendered as `c_int`, here:
https://github.com/Snektron/vulkan-zig/blob/caf8e6be99e37fd6b5f78e33f2b96a18d4a10260/generator/vulkan/render.zig#L803

It is my understanding that although Vulkan obviously is defined as a C API, and therefore must adhere to the quirks of C, it also defines a pretty strict set of parameters that must be adhered to by the execution model, such as ensuring that the type of the value underlying C enums are 32 bits in size, implied/described by the vulkan spec under point [3.7.2, "Implicit Valid Usage: Valid Usage for Enumerated Types"](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap3.html#fundamentals-validusage-enums). To quote:

> This special value exists only to ensure that C enum types are 32 bits in size. It is not part of the API, and should not be used by applications

Which is in reference to the special value for enumerations in Vulkan, which are suffixed '_MAX_ENUM', which take on the maximum value representable by a signed 32 bit integer `0x7FFFFFFF` (as far as I've seen in generated header files).
Taking all this into account, I think it may be of some benefit to render the enumerations as explicitly bit-sized integers, e.g. change the aforementioned line to something like `try self.writer.writeAll(" = enum(i32) {"); `.

But now, given that the only two enumeration types (of which I am aware) that contain negative values are `VkResult` and `VkQueryResultStatusKHR`, maybe we could also consider making the default tag type `u32`? And add some logic to set the tag type to `i32` if any negative values are found to be contained within the enumeration; otherwise I could make this a pretty quick pull request without too much more hassle (one line change). 

Thoughts? I've stewed on this for a little while, and felt a need to put this out there to get it out of my head. Feel free to close this if it's out of the scope of this project. It could set a fair baseline for what is and what isn't an objective here.

**Comment by Snektron** [comment]
I actually recently changed this in 79d901a to c_int, but i didn't really think about it. You are technically right in that it should be a 32-bit integer, but i do like to note that in C the backing type of an enum is a regular `int`, so Khronos is likely to have problems with vulkan on 16-bit platforms anyway ;). I don't think there is any particular value in enforcing unsigned numbers here, though.

**Comment by InKryption** [comment]
Righty-ho, sounds fair to me.
