### ISSUE TITLE
PfnAllocationFunction and PfnReallocationFunction should return ?*c_void, not *c_void

### ISSUE THREAD

**Issue by silversquirl** [Snektron/vulkan-zig#32]
The memory allocation chapter of the vulkan spec states:

> If pfnAllocation is unable to allocate the requested memory, it must return NULL

However, vulkan-zig's declaration for `PfnAllocationFunction` has return type `*c_void`, meaning `null` cannot be returned.

**Comment by Snektron** [comment]
For normal commands, pointers in vk.xml are generally non-optional. Optional pointers are encoded by additional xml metadata, which is lacking for function pointers. This causes the default (non optional) to be assumed everywhere.

For now i think that the best approach is to set pointers in function pointers as optional-by-default, but a proper fix would be to add this information to vk.xml. I'll see about that later maybe though.

**Comment by Snektron** [comment]
Fixed for now in 7c2d1d466be071261a5e3d9641c4c6738bda0c81 and 0fffe145ed8e12dfee687fa6ec1bd7f696053bd2.
