### ISSUE TITLE
cmdPipelineBarrier expects all barrier pointers to be present

### ISSUE THREAD

**Issue by obiwanus** [Snektron/vulkan-zig#40]
Maybe I'm misunderstanding something, but here's the definition of the `cmdPipelineBarrier` function:
```
pub fn cmdPipelineBarrier(
    self: Self,
    command_buffer: CommandBuffer,
    src_stage_mask: PipelineStageFlags,
    dst_stage_mask: PipelineStageFlags,
    dependency_flags: DependencyFlags,
    memory_barrier_count: u32,
    p_memory_barriers: [*]const MemoryBarrier,
    buffer_memory_barrier_count: u32,
    p_buffer_memory_barriers: [*]const BufferMemoryBarrier,
    image_memory_barrier_count: u32,
    p_image_memory_barriers: [*]const ImageMemoryBarrier,
) void
```
If we only want to use an image memory barrier, then we would pass `0` to `memory_barrier_count` and `buffer_memory_barrier_count`, but the pointers to the corresponding arrays are not optional, so we'd have to trick Zig and hide the fact that we're passing `null` to those pointers.

Maybe it would be possible to make those pointers optional instead?

**Comment by Snektron** [comment]
So far my strategy for these was to set the pointers which aren't used to `undefined`:
```zig
vkd.cmdPipelineBarrier(
  ...,
  .memory_barrier_count = 0,
  .p_memory_barriers = undefined,
```
I thought this was good enough until i read this article: https://zeux.io/2019/07/17/serializing-pipeline-cache/
> The reason why zero-size files are particularly interesting is that there is at least one driver version that we’ve ran into where passing a non-NULL pInitialData and initialDataSize == 0 returns an error during pipeline cache creation. Which brings us to the final caveat.

Perhaps its a good idea to introduce this feature anyway, though it would have to be on __all__ pointers and not just the ones which are truly optional.

**Comment by obiwanus** [comment]
Thanks, I didn't realise I could just pass `undefined` directly to the function. But yes, if I understand it correctly, nothing prevents the implementation to check those pointers for null and do something based on that, unless the spec explicitly prohibits it.

**Comment by Snektron** [comment]
I'm pretty sure the spec does prohibit it... that article is just talking about buggy drivers.

**Comment by obiwanus** [comment]
I will then close this issue because if the solution is to make all pointers optional then it'd be a big feature to implement. Thanks for your help!

**Comment by lefp** [comment]
Could you generate the pointer parameters as optional when their associated lengths in the XML are optional?

From `vkCmdPipelineBarrier`:
```xml
<param optional="true"><type>uint32_t</type> <name>memoryBarrierCount</name></param>
<param len="memoryBarrierCount">const <type>VkMemoryBarrier</type>* <name>pMemoryBarriers</name></param>
<param optional="true"><type>uint32_t</type> <name>bufferMemoryBarrierCount</name></param>
<param len="bufferMemoryBarrierCount">const <type>VkBufferMemoryBarrier</type>* <name>pBufferMemoryBarriers</name></param>
<param optional="true"><type>uint32_t</type> <name>imageMemoryBarrierCount</name></param>
<param len="imageMemoryBarrierCount">const <type>VkImageMemoryBarrier</type>* <name>pImageMemoryBarriers</name></param>
```

The XML for `VkDependencyInfo` has a similar pattern: the lengths are marked optional and the pointers are not. And the current binding generator correctly produces optional pointers for the struct members:
```
memory_barrier_count: u32 = 0,
p_memory_barriers: ?[*]const MemoryBarrier2 = null,
buffer_memory_barrier_count: u32 = 0,
p_buffer_memory_barriers: ?[*]const BufferMemoryBarrier2 = null,
image_memory_barrier_count: u32 = 0,
p_image_memory_barriers: ?[*]const ImageMemoryBarrier2 = null,
```

**Comment by lefp** [comment]
> Zig has no default parameters. Or do you suggest to pass the parameters via a struct instead?

What I'm proposing is: when the `len` of a pointer is `optional`, the generated pointer should be nullable.
For example:
```xml
<param optional="true"><type>uint32_t</type> <name>memoryBarrierCount</name></param>
<param len="memoryBarrierCount">const <type>VkMemoryBarrier</type>* <name>pMemoryBarriers</name></param>
```
Here `memoryBarrierCount` is an `optional` scalar (i.e. it can be 0, according to the [schema](https://registry.khronos.org/vulkan/specs/1.3/registry.html#tag-command:param:attr)).
Since `pMemoryBarriers` has `len="memoryBarrierCount"`, we can generate the parameter type `?[*]` instead of `[*]`.

Does that make sense?

**Comment by lefp** [comment]
It looks like you're already doing this...
`generator/vulkan/parse.zig`:
```zig
fn parsePointerMeta(fields: Fields, type_info: *registry.TypeInfo, elem: *xml.Element) !void {
    if (elem.getAttribute("len")) |lens| { // NOTE(lefp): if pointer has a length attribute
        var it = mem.split(u8, lens, ",");
        var current_type_info = type_info;
        while (current_type_info.* == .pointer) {
            // TODO: Check altlen
            const size = if (it.next()) |len_str| blk: {
                const size_optional = lenToPointer(fields, len_str);
                current_type_info.pointer.is_optional = size_optional[1]; // NOTE(lefp): sets nullable based on `lenToPointer`
                break :blk size_optional[0];
            } else .many;
    ...
```
If the XML entry for a pointer has a `len=elemCount` field, this calls `lenToPointer` which finds the `elemCount` field and then tells you whether the pointer is optional (based on whether `elemCount` is optional).

So this already partially works. Specifically, it works for pointers which are struct members, but not for pointers which are procedure parameters.
```zig
// returns .{ size, nullable }
fn lenToPointer(fields: Fields, len: []const u8) std.meta.Tuple(&.{ registry.Pointer.PointerSize, bool }) {
    switch (fields) {
        .command => |params| {
            for (params) |*param| {
                if (mem.eql(u8, param.name, len)) {
                    param.is_buffer_len = true;
                    return .{ .{ .other_field = param.name }, false }; // NOTE(lefp): always returns false for procedure parameters!
                }
            }
        },
        .container => |members| {
            for (members) |*member| {
                if (mem.eql(u8, member.name, len)) {
                    member.is_buffer_len = true;
                    return .{ .{ .other_field = member.name }, member.is_optional }; // NOTE(lefp): works fine for struct members
                }
            }
        },
    }
    ...
```

So we need to fix `return .{ .{ .other_field = param.name }, false };` to `return .{ .{ .other_field = param.name }, param.is_optional };`.
Although `member` (type `registry.Container.Field`) has a member `is_optional`, `param` (type `registry.Command.Param`) currently doesn't, so we'll need to add that member. I *think* that shouldn't be hard?

I can try to submit a PR this week.
