### ISSUE TITLE
Duplicate error set field 'Unknown',  in GetImageViewAddressNVXError

### ISSUE THREAD

**Issue by PiergiorgioZagaria** [Snektron/vulkan-zig#43]
I've been following vulkan-tutorial.com in the recent days and today after updating to the latest zig compiler, I got this error while compiling. Basically there is a 'VK_ERROR_UNKNOWN' in the errors and in the function "renderErrorSet" in the file "generator/vulkan/render.zig" it writes 'Unknown' unconditionally at the end. Thus contrasting with the 'Unknown' of vk_error ....

A quick fix I made to continue is this

 ```
fn renderErrorSet(self: *Self, errors: []const []const u8) !void {
            try self.writer.writeAll("error{");
            for (errors) |name| {
                /////////////////////////////////////////
                const error_unknown = "VK_ERROR_UNKNOWN";
                if (name.len == error_unknown.len and std.mem.eql(u8, name, error_unknown)) {
                     continue;
                 }
               /////////////////////////////////////////
                try self.renderResultAsErrorName(name);
                try self.writer.writeAll(", ");
            }
            try self.writer.writeAll("Unknown, }");
        }
```

With this it now works, I guess it wasn't an error in earlier versions of the compiler?

**Comment by Snektron** [comment]
Should be closed in aac20d107a9c04a09dd756d7b5e1edacc0cf23a0
