### ISSUE TITLE
Compile error on windows

### ISSUE THREAD

**Issue by kdchambers** [Snektron/vulkan-zig#45]
Hi, I'm getting a compile error when I run zig build test using master zig under Windows.

**Steps to reproduce**: `zig build test` 

**Error**:

```
C:\Users\kdcha\Documents\vulkan-zig\generator\vulkan\c_parse.zig:572:92: error: expected ',' after argument
        \\<root>// comment <name>commented name</name> <type>commented type</type> trailing
                                                                                           ^
C:\Users\kdcha\Documents\vulkan-zig\generator\vulkan\c_parse.zig:573:71: note: invalid byte: ')'
        \\    typedef void (VKAPI_PTR *<name>PFN_vkVoidFunction</name>)(void);
                                                                      ^
C:\Users\kdcha\Documents\vulkan-zig\generator\vulkan\render.zig:11:88: error: expected ';' after declaration
    \\// This file is generated from the Khronos Vulkan XML API registry by vulkan-zig.
                                                                                       ^
C:\Users\kdcha\Documents\vulkan-zig\generator\vulkan\render.zig:12:3: note: invalid byte: ' '
    \\
```

**Zig version**: 0.10.0-dev.1929+963ac6091
**vulkan-zig version**: Master 2f2125046c42fb542c9050de40f76a95745245cc

**Comment by Snektron** [comment]
This is a problem with windows-style line endings which are not supported by Zig. You should be able to set Git to clone the project using .gitattributes, or run zig fmt to have that replace them for you.

**Comment by kdchambers** [comment]
I had tried zig fmt but indeed recloning with the correct endings fixed it. Thanks for the quick and helpful response and apologies for the misfiled issue. Not used to developing on Windows, just testing my project to see if it works. This can be closed.

**Comment by a-day-old-bagel** [comment]
I appreciate that this issue exists, because I was having a very confusing time for a minute wondering why on earth the multiline comment was breaking.

Developing on Windows is such a mess.

**Comment by Snektron** [comment]
This is true, and im also not sure why it happens. One related thing is that some windows CI should probably be set up at some point...
