### ISSUE TITLE
Command flags should be mergeable

### ISSUE THREAD

**Issue by ashpil** [Snektron/vulkan-zig#47]
Seems this never made it after the duck typing verification PR.

https://github.com/Snektron/vulkan-zig/pull/35#issuecomment-1142812180

**Comment by InKryption** [comment]
In looking into doing this, I've come to realize that the `{}Command` enums are actually somewhat redundant at this point... They only real function they appear to serve is for using the `symbol` and `PfnType` functions, which, in all honesty, could be pretty easily inlined, or have their results computed during rendering. I think I might try this.
