### ISSUE TITLE
Example: is defer inside initSwapchainImages correct?

### ISSUE THREAD

**Issue by viviicat** [Snektron/vulkan-zig#49]
Pardon me if this makes no sense, as I am brand new to Vulkan and also Zig. However, I was wondering if the `defer` in this line ought to be an `errdefer` instead? It doesn't make sense to me that we would deallocate the vkImage memory inside the init function and then pass the pointer out.

https://github.com/Snektron/vulkan-zig/blob/fdf43d846a4c3ff4d977bd4395898e4e16ca62cf/examples/swapchain.zig#L253-L257

**Comment by viviicat** [comment]
Ah I get it. It's the *list* that is being deallocated.

**Comment by Snektron** [comment]
Yes, temporary storage is needed because the call to Vulkan does not accept the swap_images memory directly.
