### ISSUE TITLE
Function with C calling convention should not have arrays as parameters

### ISSUE THREAD

**Issue by nolanderc** [Snektron/vulkan-zig#54]
I ran into this issue trying to compile:
```zig
const DeviceDispatch = vk.DeviceWrapper(.{
    // ...
    .cmdSetBlendConstants = true,
});
```
I get the error
```
./zig-cache/vk.zig:13449:5: error: parameter of type '[4]f32' not allowed in function with calling convention 'C'
    blend_constants: [4]f32,
    ^~~~~~~~~~~~~~~~~~~~~~~
```
which is caused by this declaration (later used as the type of the dispatcher field):
```zig
pub const PfnCmdSetBlendConstants = *const fn (
    command_buffer: CommandBuffer,
    blend_constants: [4]f32,
) callconv(vulkan_call_conv) void;
```
In my case `vulkan_call_conv == .C`.

This type corresponds to [this function](https://registry.khronos.org/VulkanSC/specs/1.0-extensions/man/html/vkCmdSetBlendConstants.html):
```
void vkCmdSetBlendConstants(
    VkCommandBuffer                             commandBuffer,
    const float                                 blendConstants[4]);
```
But notably, this is not an array of 4 floats, but a pointer to a value of 4 floats. Seems like a bug in the generator code?

**Comment by Snektron** [comment]
Ah yes, these arrays should be converted to pointers. Thanks for reporting.

**Comment by Snektron** [comment]
Turned out to be easier than expected. Sorry for the wait
