### ISSUE TITLE
sometimes nested pointer parsing is incorrect

### ISSUE THREAD

**Issue by ashpil** [Snektron/vulkan-zig#59]
I noticed this in `vkCmdBuildAccelerationStructuresKHR` -- vulkan-zig expects the `ppBuildRangeInfos` field to be `[*]const *const vk.AccelerationStructureBuildRangeInfoKHR`, whereas it should be `[*]const [*]const vk.AccelerationStructureBuildRangeInfoKHR`.

Haven't spent enough time looking at the pointer-parsing code to see why this might be, or what other cases this might affect. It seems that vk.xml doesn't provide useful information here.

**Comment by Snektron** [comment]
Sorry for not responding - vulkan-zig infers whether a pointer should me many or single from the `len` attribute on a `<param>` tag in a command. This is a comma-separated list of things that indicate the length of each rank of the pointer, usually an expression or `null-terminated`. It looks like in the case of vkCmdBuildAccelerationStructuresKHR there is only one such name, and so the fallback - single a item pointer - is chosen for the inner type.

**Comment by Snektron** [comment]
Seems like there are a number of similar cases, and theyre all resolved by changing the fallback from a single-item pointer to many. I guess its not really a proper solution, but given that there seem to be no regressive cases it seems fine to me.

**Comment by ashpil** [comment]
Makes sense to me, the fallback is used when you don’t know anything, so it should be the most general thing.

**Comment by Snektron** [comment]
fixed in https://github.com/Snektron/vulkan-zig/commit/be59386118ce51418ff710a5d6220d1c560f6338
