### ISSUE TITLE
Stdcall fix was incorrectly implemented

### ISSUE THREAD

**Issue by Sethughes** [Snektron/vulkan-zig#6]
In the render preamble `builtin.os.arch` is used, which should be `builtin.cpu.arch`. Zig 7.x and 7.x+ throw errors for a missing member when vk.zig is compiled.
```sh
.\zig-cache\vk.zig:12:102: error: no member named 'arch' in struct 'std.target.Os'
pub const vulkan_call_conv: builtin.CallingConvention = if (builtin.os.tag == .windows and builtin.os.arch == .i386)
                                                                                                     ^
```
Here in render.zig:
https://github.com/Snektron/vulkan-zig/blob/1299a828d52c07f46d4b5307541272b8b6a28809/generator/vulkan/render.zig#L17

I believe this was just a misprint of the solution offered a month ago in a zig compiler issue:
[zigland/zig/issues#7337](https://github.com/ziglang/zig/issues/7337)
[LemonBoy's Fix](https://github.com/ziglang/zig/issues/7337#issuecomment-740776948)
> Thanks for the bug report, the problem is a missing check in the compiler.
> What the compiler is trying to tell you is that the definition of `vulkan_call_conv` is incorrect when targeting Windows, `.Stdcall` is only valid for 32bit targets.
> The fix is to change `if (builtin.os.tag == .windows)` into `if (builtin.os.tag == .windows and builtin.arch == .i386)`.
> 
> One more detail, `extern "c"` means this function is externally defined and is provided by ... `libc`?
> The value between the `""` has no effect beside adding `c` to the list of required libraries, it's working just fine here as it becomes a no-op given you already link against libc.

Unfortunately, when fixed, this throws another internal compiler error in windows, but that's on zig.

**Comment by Snektron** [comment]
Thanks for the report. Perhaps (when the compiler issue is fixed) i should finally set up Windows CI as well.
