### ISSUE TITLE
Wishlist: some way to deal with shader files that use imports 

### ISSUE THREAD

**Issue by ashpil** [Snektron/vulkan-zig#70]
My project contains a lot of shader files and a lot of shader files that import other shader files. The current caching mechanism has no way to tell when a shader file imported by another shader file has changed and thus recompilation must commence.

It seems there's three ways to solve it, in order of increasing difficulty:

- Allow disabling shader compilation caching
- Allow manually specifying files that a certain shader file "depends on", i.e., files that should be watched as well and changes to them trigger recompilation
- Somehow actually automatically trace the shader import tree

Of these, the second option seems the most reasonable to me and I'd be happy to implement it if you agree.

**Comment by Snektron** [comment]
Yes, this is a valid concern and I agree that there should be an improvement.

> It seems there's three ways to solve it, in order of increasing difficulty:
> [...]
> * Somehow actually automatically trace the shader import tree

It looks like both dxc and glslc support the `-M` family of flags, allowing us to capture this trace from the compiler directly (note: glslangValidator doesn't implement `#include`). This is still compiler specific, though, but at least its a fairly standard flag. I think the ideal solution would use this, but yes, it is also harder to implement and could potentially limit the compilers that can be used with this feature.

In the mean time, Im fine with either of the solutions if they are hindering your workflow. I think disabling the caching mechanism will have no effect on correctness, if a particular include statement would resolve to a different flag then the compile commands would be different... I guess the hash for the output file can even be derived solely from the compile commands in that case as well. 

To be honest, this shader compilation feature was always meant as a small bonus (to help compiling the example) and not really as an integral feature of the binding generator, though as long as there is not a proper alternative I want to keep it. Perhaps some day it can be split out to a separate project...
