### ISSUE TITLE
KHR versions of dynamic rendering

### ISSUE THREAD

**Issue by rongcuid** [Snektron/vulkan-zig#71]
This package only generates the Vulkan 1.3 variant of dynamic rendering functions (`vkCmdBeginRendering`, etc). However, on some drivers supporting only Vulkan 1.2 (namely MoltenVK), these functions are NULL, but KHR variants (`vkCmdBeginRenderingKHR`, etc) are valid.

**Comment by Snektron** [comment]
This is indeed unintentional. The fix in vulkan-zig for this is to, wherever commands are processed, to first resolve all aliases.

As a temporary fix you can use a vk.xml for version 1.2.

**Comment by Snektron** [comment]
I've improved the way aliases are generated in https://github.com/Snektron/vulkan-zig/commit/8b452b9edd17841dff75c04cd5f9f20554904cff. Now dynamic rendering should actually be usable on older Vulkan implementations.
