### ISSUE TITLE
No mention of required zig verison in readme

### ISSUE THREAD

**Issue by Avokadoen** [Snektron/vulkan-zig#8]
Running `zig build run-triangle` in root with zig version 0.7.1 results in the following error
```txt
.\generator\id_render.zig:148:39: error: container 'std.zig' has no member called 'fmtId'
        try out.print("{}", .{ std.zig.fmtId(self.text_cache.items) });
...
```

I'm guessing this project requires the latest master, but it would be nice if it was mentioned somewhere 😅

**Comment by Snektron** [comment]
Ah good point. My idea was to also create tags for major Zig releases, i will do that too.

**Comment by Snektron** [comment]
Alright, i've written a small clarification on the required Zig versions for this projects, as well as created a tag that points to a version that should be compatible with Zig 0.7.1. I've cherry picked some commits after the one which breaks 0.7.1 compatibility, see https://github.com/Snektron/vulkan-zig/tree/zig-0.7.1

**Comment by Avokadoen** [comment]
> 
> 
> Alright, i've written a small clarification on the required Zig versions ...

Awesome. Thanks for making this awesome project :D
