### ISSUE TITLE
Using KHR version of a vk function instead of non KHR

### ISSUE THREAD

**Issue by citruslee** [Snektron/vulkan-zig#83]
Hey. In Vulkan 1.2 there was an extension Dynamic Rendering, getting rid of all the renderpass stuff which is absolutely unnecessary. In Vulkan 1.3 they elevated into core, therefore they dropped the KHR from the end of it. But some vulkan drivers (namely MoltenVK) has no 1.3 support. I see that there was another thread about this feature, but actually using 1.2 vulkan xml for generating really does not work at all. We need the methods generated from the XML. Now we actually figured an easier fix, which is basically duplicating the xml tag and writing KHR at the end, but this somehow seems to break some other functions, like setdebugobjectname. 

`src/rhi/vulkan/vk.zig:31428:26: error: no field or member function named 'vkCmdBeginRendering' in 'rhi.vulkan.vk.DeviceWrapper(.{.destroyDevice = true, .getDeviceQueue = true, .queueSubmit = true, .queueWaitIdle = true, .deviceWaitIdle = true, .allocateMemory = true, .freeMemory = true, .mapMemory = true, .unmapMemory = true, .flushMappedMemoryRanges = false, .invalidateMappedMemoryRanges = false, .getDeviceMemoryCommitment = false, .getBufferMemoryRequirements = true, .bindBufferMemory = true, .getImageMemoryRequirements = false, .bindImageMemory = false, .getImageSparseMemoryRequirements = false, .queueBindSparse = false, .createFence = true, .destroyFence = true, .resetFences = true, .getFenceStatus = false, .waitForFences = true, .createSemaphore = true, .destroySemaphore = true, .createEvent = false, .destroyEvent = false, .getEventStatus = false, .setEvent = false, .resetEvent = false, .createQueryPool = false, .destroyQueryPool = false, .getQueryPoolResults = false, .resetQueryPool = false, .resetQueryPoolEXT = false, .createBuffer = true, .destroyBuffer = true, .createBufferView = false, .destroyBufferView = false, .createImage = false, .destroyImage = false, .getImageSubresourceLayout = false, .createImageView = true, .destroyImageView = true, .createShaderModule = true, .destroyShaderModule = true, .createPipelineCache = false, .destroyPipelineCache = false, .getPipelineCacheData = false, .mergePipelineCaches = false, .createGraphicsPipelines = true, .createComputePipelines = false, .getDeviceSubpassShadingMaxWorkgroupSizeHUAWEI = false, .destroyPipeline = true, .createPipelineLayout = true, .destroyPipelineLayout = true, .createSampler = false, .destroySampler = false, .createDescriptorSetLayout = true, .destroyDescriptorSetLayout = true, .createDescriptorPool = true, .destroyDescriptorPool = true, .resetDescriptorPool = false, .allocateDescriptorSets = true, .freeDescriptorSets = false, .updateDescriptorSets = true, .createFramebuffer = true, .destroyFramebuffer = true, .createRenderPass = true, .destroyRenderPass = true, .getRenderAreaGranularity = false, .createCommandPool = true, .destroyCommandPool = true, .resetCommandPool = false, .allocateCommandBuffers = true, .freeCommandBuffers = true, .beginCommandBuffer = true, .endCommandBuffer = true, .resetCommandBuffer = true, .cmdBindPipeline = true, .cmdSetViewport = true, .cmdSetScissor = true, .cmdSetLineWidth = false, .cmdSetDepthBias = false, .cmdSetBlendConstants = false, .cmdSetDepthBounds = false, .cmdSetStencilCompareMask = false, .cmdSetStencilWriteMask = false, .cmdSetStencilReference = false, .cmdBindDescriptorSets = true, .cmdBindIndexBuffer = false, .cmdBindVertexBuffers = true, .cmdDraw = true, .cmdDrawIndexed = false, .cmdDrawMultiEXT = false, .cmdDrawMultiIndexedEXT = false, .cmdDrawIndirect = false, .cmdDrawIndexedIndirect = false, .cmdDispatch = false, .cmdDispatchIndirect = false, ...}).Dispatch__struct_26766'
            self.dispatch.vkCmdBeginRendering(`
            
this is how the error looks like. If I can be of more assistance, I will happily give it to you, since we need this to be fixed, since we want to release our demo to the masses, but it just does not compile with the latest vulkan SDK. I will provide even the full source code to it so you can test it out.

**Comment by Snektron** [comment]
I think https://github.com/Snektron/vulkan-zig/commit/8b452b9edd17841dff75c04cd5f9f20554904cff should work for your use case - Wrappers are now generated for the aliases as well, rather than just generating an alias in Zig.

**Comment by bndbsh** [comment]
I'm running into this issue with `vkCmdPipelineBarrier2`. If I specify it in the wrapper, it fails to load at runtime as expected. However, if I don't specify `vkCmdPipelineBarrier2`, I get this error:

```
src/vk.zig:31701:26: error: no field or member function named 'vkCmdPipelineBarrier2' in 'vk.DeviceWrapper(.{.destroyDevice = true, .getDeviceQueue = true, .queueSubmit = true, .queueWaitIdle = true, .deviceWaitIdle = true, .allocateMemory = true, .freeMemory = true, .mapMemory = true, .unmapMemory = true, .flushMappedMemoryRanges = false, .invalidateMappedMemoryRanges = false, .getDeviceMemoryCommitment = false, .getBufferMemoryRequirements = true, .bindBufferMemory = true, .getImageMemoryRequirements = true, .bindImageMemory = true, .getImageSparseMemoryRequirements = false, .queueBindSparse = false, .createFence = true, .destroyFence = true, .resetFences = true, .getFenceStatus = false, .waitForFences = true, .createSemaphore = true, .destroySemaphore = true, .createEvent = false, .destroyEvent = false, .getEventStatus = false, .setEvent = false, .resetEvent = false, .createQueryPool = false, .destroyQueryPool = false, .getQueryPoolResults = false, .resetQueryPool = false, .resetQueryPoolEXT = false, .createBuffer = true, .destroyBuffer = true, .createBufferView = false, .destroyBufferView = false, .createImage = true, .destroyImage = true, .getImageSubresourceLayout = false, .createImageView = true, .destroyImageView = true, .createShaderModule = true, .destroyShaderModule = true, .createPipelineCache = false, .destroyPipelineCache = false, .getPipelineCacheData = false, .mergePipelineCaches = false, .createGraphicsPipelines = true, .createComputePipelines = false, .getDeviceSubpassShadingMaxWorkgroupSizeHUAWEI = false, .destroyPipeline = true, .createPipelineLayout = true, .destroyPipelineLayout = true, .createSampler = true, .destroySampler = true, .createDescriptorSetLayout = true, .destroyDescriptorSetLayout = true, .createDescriptorPool = true, .destroyDescriptorPool = true, .resetDescriptorPool = false, .allocateDescriptorSets = true, .freeDescriptorSets = false, .updateDescriptorSets = true, .createFramebuffer = true, .destroyFramebuffer = true, .createRenderPass = true, .destroyRenderPass = true, .getRenderAreaGranularity = false, .createCommandPool = true, .destroyCommandPool = true, .resetCommandPool = true, .allocateCommandBuffers = true, .freeCommandBuffers = true, .beginCommandBuffer = true, .endCommandBuffer = true, .resetCommandBuffer = true, .cmdBindPipeline = true, .cmdSetViewport = true, .cmdSetScissor = true, .cmdSetLineWidth = false, .cmdSetDepthBias = false, .cmdSetBlendConstants = false, .cmdSetDepthBounds = false, .cmdSetStencilCompareMask = false, .cmdSetStencilWriteMask = false, .cmdSetStencilReference = false, .cmdBindDescriptorSets = true, .cmdBindIndexBuffer = false, .cmdBindVertexBuffers = true, .cmdDraw = true, .cmdDrawIndexed = false, .cmdDrawMultiEXT = false, .cmdDrawMultiIndexedEXT = false, .cmdDrawIndirect = false, .cmdDrawIndexedIndirect = false, .cmdDispatch = false, .cmdDispatchIndirect = false, ...}).Dispatch__struct_27658'
```

This happens anytime `cmdPipelineBarrier2` is not set to `true` in the dispatch struct, regardless of whether I attempt to load the KHR version or not. I guess this is because it's now generating code for both the KHR and 1.3 versions of the command, and the latter fails to build? Or maybe I'm doing something else wrong?

I generated vk.zig using vulkan-zig from master and vk.xml 1.3.249, running on MoltenVK.

**Comment by bndbsh** [comment]
Ignore that, there was some code calling into `cmdPipelineBarrier2` directly that I didn't update.
