### ISSUE TITLE
Package manager support

### ISSUE THREAD

**Issue by LordMZTE** [Snektron/vulkan-zig#85]
It'd be great to be able to build vulkan-zig with the package manager instead of having to use submodules.

**Comment by Snektron** [comment]
As far as I understand, you should already be able to use vulkan-zig with the current package manager tooling. Is there a specific feature missing, or is this issue just to track future development on the Zig side?

**Comment by LordMZTE** [comment]
Sorry, I saw this project in another library which used the generator API and added the resulting module, but I missed that the vulkan bindings would be generated by the build script. I though it did something like `@import("vulkan").getModule()` which used to be a common antipattern. My bad!
